name: 'Setup Nix environment'

runs:
  using: "composite"
  steps:
    - name: Install Nix
      uses: cachix/install-nix-action@v30
      with:
        github_access_token: ${{ github.token }}

    - name: Setup Magic Nix Cache
      uses: DeterminateSystems/magic-nix-cache-action@v8