name: Lint & Check Flake

on: [ push, pull_request, workflow_dispatch ]

jobs:
  # Run an check for flake.lock
  flake-health:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Nix
        uses: ./.github/setup
      - name: Check flake health
        uses: DeterminateSystems/flake-checker-action@v9

  # The main check. Checks flake.nix
  check-flake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Nix
        uses: ./.github/setup
      - name: Check flake
        run: nix flake check --all-systems

  # Checks if Leaf builds
  build-leaf:
    runs-on: ubuntu-latest
    needs: [ flake-health, check-flake ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Nix
        uses: ./.github/setup
      - name: Check if Leaf builds
        run: nix build .#leaf

  # Build all wallpapers in a single step
  build-wallpapers:
    runs-on: ubuntu-latest
    needs: [ flake-health, check-flake ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Nix
        uses: ./.github/setup-cacheless
      - name: Build Wallpapers
        run: |
          nix build .#Abstract
          nix build .#BetterSonoma
          nix build .#Black
          nix build .#Flow
          nix build .#SteamAutumn
          nix build .#SteamSpring
          nix build .#SteamSummer
