name: Lint & Check Flake

on: [push, pull_request, workflow_dispatch]

jobs:
  flake-health:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/setup/action.yaml
      - name: Check flake health
        uses: DeterminateSystems/flake-checker-action@v9

  check-flake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/setup/action.yaml
      - name: Run Checks
        run: nix flake check --all-systems