name: Lint & Check Flake

on: [push, pull_request, workflow_dispatch]

jobs:
  flake-health:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Nix
        uses: ./.github/setup

      - name: Check flake health
        uses: DeterminateSystems/flake-checker-action@v9

  check-flake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Nix
        uses: ./.github/setup

      - name: Check flake
        run: nix flake check --all-systems

  check-leaf:
    runs-on: ubuntu-latest
    needs: [ flake-health, check-flake ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Nix
        uses: ./.github/setup

      - name: Check if Leaf builds
        run: nix build .#leaf

